- apiVersion: v1
  kind: Service
  metadata:
    namespace: infra
    name: proxy
    labels:
      app: proxy
  spec:
    selector:
      app: proxy
    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP
      - name: https
        port: 443
        targetPort: 443
        protocol: TCP
    type: LoadBalancer
