apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: ns
  name: one
spec:
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
        - name: one
          image: 'repo/one:latest'
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 200m
