apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: heapster
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: heapster
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
        - name: heapster
          image: 'gcr.io/google_containers/heapster-amd64:v1.3.0'
          env: []
          ports: []
          resources:
            requests:
              memory: 50Mi
              cpu: 0.1
            limits:
              memory: 200Mi
              cpu: 0.2
          command:
            - /heapster
            - '--source=kubernetes:https://kubernetes.default'
            - '--sink=influxdb:http://influxdb.data:8086'
