apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: ns
  name: three
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: three
    spec:
      containers:
        - name: three
          image: 'repo/three:latest'
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: ns
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
