apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: ns
  name: two
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
        - name: two
          image: 'repo/two:latest'
          resources:
            requests:
              memory: 250Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 250m
